// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjrcvmxvzjyjqjibwnra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcmN2bXh2emp5anFqaWJ3bnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDgwNTIsImV4cCI6MjA2ODQyNDA1Mn0.2TKkfa8F6Sn4T4jW_VZs0_zAb9Tt7iiEe_zsJY4iJgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});